v1 prettified with gamma workflow

diff --git a/.github/workflows/packaging-pr.yml b/.github/workflows/packaging-pr.yml
--- a/.github/workflows/packaging-pr.yml
+++ b/.github/workflows/packaging-pr.yml
@@ -24,11 +24,19 @@ jobs:
       - name: "Checkout source code"
         uses: actions/checkout@v2
 
+      # Install Volta to enforce proper node and package manager versions
+      - name: "Install Volta"
+        uses: volta-cli/action@v1
+
+      # Generate omnistudio versions of source
+      - name: "Automatically generate Omnistudio source"
+        run: node ./osfilegen.js
+
       # Store secret for dev hub
       - name: "Populate auth file with DEVHUB_SFDX_URL secret"
         shell: bash
         run: |
-          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+          echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
           secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
           if [ $secretFileSize == 1 ]; then
               echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
@@ -44,11 +52,44 @@ jobs:
         run: rm -f ./DEVHUB_SFDX_URL.txt
 
       # Create package version and extract its id
-      - name: "Create package version"
-        id: createPackageVersion
+      - name: "Create package version sfGpsDs"
+        id: createPackageVersion-sfGpsDs
+        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
         run: |
           set +e
-          json=$(sfdx force:package:version:create -p sfGpsDs -x -w 20 -f config/project-scratch-def.json --json)
+          json=$(sfdx force:package:version:create -d sfGpsDs -x -w 20 -f config/project-scratch-def.json --json)
+          echo $json
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "::set-output name=packageVersionId::$packageVersionId"
+          else
+              echo "sfdx force:package:version:create failed"
+          fi
+          exit $status
+
+      - name: "Create package version sfGpsDsAuNsw"
+        id: createPackageVersion-sfGpsDsAuNsw
+        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
+        run: |
+          set +e
+          json=$(sfdx force:package:version:create -d sfGpsDsAuNsw -x -w 20 -f config/project-scratch-def.json --json)
+          echo $json
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "::set-output name=packageVersionId::$packageVersionId"
+          else
+              echo "sfdx force:package:version:create failed"
+          fi
+          exit $status
+
+      - name: "Create package version sfGpsDsAuNswS"
+        id: createPackageVersion-sfGpsDsAuNswS
+        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
+        run: |
+          set +e
+          json=$(sfdx force:package:version:create -d sfGpsDsAuNswS -x -w 20 -f config/project-scratch-def.json --json)
           echo $json
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
@@ -69,9 +110,29 @@ jobs:
       - name: "Create scratch org"
         run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
 
-      # Install new package in scratch org
-      - name: "Install new package version in scratch org"
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion.outputs.packageVersionId }} -w 10 -u scratch-org -r
+      # Deploy omnistudio to scratch org
+      - name: "Deploy Omnistudio"
+        run: sfdx force:package:install -p ${{ secrets.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 10 -r -s=AllUsers
+
+      # Install new sfGpsDs package in scratch org
+      - name: "Install new sfGpsDs package version in scratch org"
+        if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 10 -u scratch-org -r
+
+      # Install old sfGpsDs package in scratch org
+      - name: "Install current sfGpsDs package version in scratch org"
+        if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
+        run: sfdx force:package:install -p "Salesforce Global Public Sector Design Systems" -w 10 -u scratch-org -r
+
+      # Install new sfGpsDsAuNsw package in scratch org
+      - name: "Install new sfGpsDsAuNsw package version in scratch org"
+        if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 10 -u scratch-org -r
+
+      # Install new sfGpsDsAuNswS package in scratch org
+      - name: "Install new sfGpsDsAuNswS package version in scratch org"
+        if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 10 -u scratch-org -r
 
       # Housekeeping
       - name: "Delete scratch org"
