adjusting uk gov build for two versions

diff --git a/.github/workflows/packaging-pr.yml b/.github/workflows/packaging-pr.yml
--- a/.github/workflows/packaging-pr.yml
+++ b/.github/workflows/packaging-pr.yml
@@ -169,6 +169,24 @@ jobs:
           fi
           exit $status
 
+      - name: "Create package version sfGpsDsUkGovFull"
+        id: createPackageVersion-sfGpsDsUkGovFull
+        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          set +e
+          json=$(sfdx force:package:version:create -d sfGpsDsUkGovFull -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
+          echo $json
+          echo "----"
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+          else
+              echo "sfdx force:package:version:create failed"
+          fi
+          exit $status
+
       # Wait for package replication
       - name: "Wait for package replication"
         uses: maddox/actions/sleep@master
