Move from eschweitzer78 to SalesforceLabs repo

diff --git a/.github/workflows/packaging-pr-prerelease.yml b/.github/workflows/packaging-pr-prerelease.yml
--- a/.github/workflows/packaging-pr-prerelease.yml
+++ b/.github/workflows/packaging-pr-prerelease.yml
@@ -11,15 +11,6 @@ jobs:
   packaging:
     runs-on: ubuntu-latest
     steps:
-      # Install Salesforce CLI
-      - name: "Install Salesforce CLI"
-        run: |
-          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
-          mkdir ~/sfdx
-          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
-          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
-          ~/sfdx/bin/sfdx version
-
       # Checkout the source code
       - name: "Checkout source code"
         uses: actions/checkout@v2
@@ -28,9 +19,49 @@ jobs:
       - name: "Install Volta"
         uses: volta-cli/action@v3
 
+      # Cache node_modules to speed up the process
+      - name: "Restore node_modules cache"
+        id: cache-npm
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            npm-${{ env.cache-name }}-
+            npm-
+
+      # Install Salesforce CLI
+      - name: "Install Salesforce CLI v7.182.1"
+        run: |
+          npm install sfdx-cli@7.182.1 --location=global
+          nodeInstallPath=$(npm config get prefix)
+          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
+
+      # Install Salesforce CLI
+      - name: "Confirm Salesforce CLI version"
+        run: |
+          sfdx --version
+
+      # Install npm dependencies for cssgen
+      - name: "Install npm dependencies"
+        if: steps.cache-npm.outputs.cache-hit != 'true'
+        run: npm ci
+
+      # Prep
+      - name: "Prepare repo"
+        run: npm run prep
+
+        # Generate css from scss
+      - name: "Automatically generate css"
+        run: npm run cssgen
+
       # Generate omnistudio versions of source
       - name: "Automatically generate Omnistudio source"
-        run: node ./osfilegen.js
+        run: npm run osfilegen
+
+      # Copy UkGovFull
+      - name: "Copy UkGovFull"
+        run: npm run ukgov-copy
 
       # Store secret for dev hub
       - name: "Populate auth file with DEVHUB_SFDX_URL secret"
@@ -57,8 +88,10 @@ jobs:
         if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
         run: |
           set +e
-          json=$(sfdx force:package:version:create -d sfGpsDs -x -w 20 -f config/project-scratch-def.json --json)
+          json=$(sfdx force:package:version:create -d sfGpsDs -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -73,8 +106,10 @@ jobs:
         if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
         run: |
           set +e
-          json=$(sfdx force:package:version:create -d sfGpsDsAuNsw -x -w 20 -f config/project-scratch-def.json --json)
+          json=$(sfdx force:package:version:create -d sfGpsDsAuNsw -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -89,8 +124,10 @@ jobs:
         if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
         run: |
           set +e
-          json=$(sfdx force:package:version:create -d sfGpsDsAuNswS -x -w 20 -f config/project-scratch-def.json --json)
+          json=$(sfdx force:package:version:create -d sfGpsDsAuNswS -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -106,7 +143,9 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsAuVic -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -122,7 +161,27 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsUkGov -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+          else
+              echo "sfdx force:package:version:create failed"
+          fi
+          exit $status
+
+      - name: "Create package version sfGpsDsUkGovFull"
+        id: createPackageVersion-sfGpsDsUkGovFull
+        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          set +e
+          json=$(sfdx force:package:version:create -d sfGpsDsUkGovFull -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
+          echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -140,43 +199,57 @@ jobs:
 
       # Create scratch org
       - name: "Create scratch org"
-        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 release=Preview
+        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
 
       # Deploy omnistudio to scratch org
       - name: "Deploy Omnistudio"
-        run: sfdx force:package:install -p ${{ secrets.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 13 -r -s=AllUsers
+        run: sfdx force:package:install -p ${{ vars.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 20 -r -s=AllUsers
 
       # Install new sfGpsDs package in scratch org
       - name: "Install new sfGpsDs package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 20 -u scratch-org -r
+
+      # Get current sfGpsDs package version
+      - name: "Get current sfGpsDs package version"
+        id: currentSfGpsDsPack
+        if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
+        run: |
+          packageVersionId=$(sfdx force:package:version:list -p 'Salesforce Global Public Sector Design Systems' -o CreatedDate --concise | tail -1 | awk '{print $3}')
+          echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
 
       # Install old sfGpsDs package in scratch org
       - name: "Install current sfGpsDs package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
-        run: sfdx force:package:install -p "Salesforce Global Public Sector Design Systems" -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.currentSfGpsDsPack.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuNsw package in scratch org
       - name: "Install new sfGpsDsAuNsw package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuNswS package in scratch org
       - name: "Install new sfGpsDsAuNswS package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuVic package in scratch org
       - name: "Install new sfGpsDsAuVic package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsUkGov package in scratch org
       - name: "Install new sfGpsDsUkGov package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} -w 20 -u scratch-org -r
+
+      # run prettier as sfdx-package.json gets overwritten in a non-prettier way
+      - name: "Run prettier"
+        run: |
+          npm ci
+          npm run prettier
 
       # Housekeeping
       - name: "Delete scratch org"
         if: always()
-        run: sfdx force:org:delete -p -u scratch-org
+        run: sfdx org delete scratch -p -o scratch-org
diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -16,15 +16,6 @@ jobs:
   release-package-version:
     runs-on: ubuntu-latest
     steps:
-      # Install Salesforce CLI
-      - name: "Install Salesforce CLI"
-        run: |
-          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
-          mkdir ~/sfdx
-          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
-          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
-          ~/sfdx/bin/sfdx version
-
       # Checkout the source code
       - name: "Checkout source code"
         uses: actions/checkout@v3
@@ -35,9 +26,49 @@ jobs:
       - name: "Install Volta"
         uses: volta-cli/action@v3
 
+      # Cache node_modules to speed up the process
+      - name: "Restore node_modules cache"
+        id: cache-npm
+        uses: actions/cache@v3
+        with:
+          path: node_modules
+          key: npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            npm-${{ env.cache-name }}-
+            npm-
+
+      # Install Salesforce CLI
+      - name: "Install Salesforce CLI v7.182.1"
+        run: |
+          npm install sfdx-cli@7.182.1 --location=global
+          nodeInstallPath=$(npm config get prefix)
+          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
+
+      # Install Salesforce CLI
+      - name: "Confirm Salesforce CLI version"
+        run: |
+          sfdx --version
+
+      # Install npm dependencies for cssgen
+      - name: "Install npm dependencies"
+        if: steps.cache-npm.outputs.cache-hit != 'true'
+        run: npm ci
+
+      # Prep
+      - name: "Prepare repo"
+        run: npm run prep
+
+        # Generate css from scss
+      - name: "Automatically generate css"
+        run: npm run cssgen
+
       # Generate omnistudio versions of source
       - name: "Automatically generate Omnistudio source"
-        run: node ./osfilegen.js
+        run: npm run osfilegen
+
+      # Copy UkGovFull
+      - name: "Copy UkGovFull"
+        run: npm run ukgov-copy
 
       # Store secret for dev hub
       - name: "Populate auth file with DEVHUB_SFDX_URL secret"
@@ -65,7 +96,9 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDs -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -81,7 +114,9 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsAuNsw -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -97,7 +132,9 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsAuNswS -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -113,7 +150,9 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsAuVic -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
@@ -129,13 +168,34 @@ jobs:
         run: |
           set +e
           json=$(sfdx force:package:version:create -d sfGpsDsUkGov -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
           echo $json
+          echo "----"
           status=$(echo $json | jq '.status')
           if [ $status == "0" ]; then
               packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
               echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
           else
               echo "sfdx force:package:version:create failed"
+          fi
+          exit $status
+
+      - name: "Create package version sfGpsDsUkGovFull"
+        id: createPackageVersion-sfGpsDsUkGovFull
+        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          set +e
+          json=$(sfdx force:package:version:create -d sfGpsDsUkGovFull -x -w 20 -f config/project-scratch-def.json --codecoverage --json)
+          echo "force:package:version:create output:"
+          echo $json
+          echo "----"
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+          else
+              echo "sfdx force:package:version:create failed"
+              ls -lR sfGpsDsUkGovFull/main/default/lwc
           fi
           exit $status
 
@@ -151,7 +211,7 @@ jobs:
 
       # Deploy omnistudio to scratch org
       - name: "Deploy Omnistudio"
-        run: sfdx force:package:install -p ${{ secrets.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 13 -r -s=AllUsers
+        run: sfdx force:package:install -p ${{ vars.OMNISTUDIO_PACKAGEID }} -u scratch-org -w 20 -r -s=AllUsers
 
       # Activate metadata for omnistudio on scratch org
       # (removed as OmniStudio metadata cannot be packaged fo now)
@@ -165,7 +225,7 @@ jobs:
       # Install new sfGpsDs package in scratch org
       - name: "Install new sfGpsDs package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Get current sfGpsDs package version
       - name: "Get current sfGpsDs package version"
@@ -173,80 +233,92 @@ jobs:
         if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
         run: |
           packageVersionId=$(sfdx force:package:version:list -p 'Salesforce Global Public Sector Design Systems' -o CreatedDate --concise | tail -1 | awk '{print $3}')
-          echo echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+          echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
 
       # Install old sfGpsDs package in scratch org
       - name: "Install current sfGpsDs package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDs == 'false' }}
-        run: sfdx force:package:install -p ${{ steps.currentSfGpsDsPack.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.currentSfGpsDsPack.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuNsw package in scratch org
       - name: "Install new sfGpsDsAuNsw package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuNswS package in scratch org
       - name: "Install new sfGpsDsAuNswS package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsAuVic package in scratch org
       - name: "Install new sfGpsDsAuVic package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
       # Install new sfGpsDsUkGov package in scratch org
       - name: "Install new sfGpsDsUkGov package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
-        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} -w 13 -u scratch-org -r
+        run: sfdx force:package:install -p ${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }} -w 20 -u scratch-org -r
 
-      # Update sfGpsDs package install link in readme
+      # Update sfGpsDs force:force:package:install link in readme
       - name: "Update package sfGpsDs install link in readme"
         if: ${{ github.event.client_payload.sfGpsDs == 'true' }}
         run: |
           packageVersionId="${{ steps.createPackageVersion-sfGpsDs.outputs.packageVersionId }}"
-          packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDs\""
-          newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDs\""
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDs\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDs\""
           sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
-      # Update sfGpsDsAuNsw package install link in readme
+      # Update sfGpsDsAuNsw force:force:package:install link in readme
       - name: "Update package sfGpsDsAuNsw install link in readme"
         if: ${{ github.event.client_payload.sfGpsDsAuNsw == 'true' }}
         run: |
           packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuNsw.outputs.packageVersionId }}"
-          packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNsw\""
-          newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNsw\""
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNsw\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNsw\""
           sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
-      # Update sfGpsDsAuNswS package install link in readme
+      # Update sfGpsDsAuNswS force:force:package:install link in readme
       - name: "Update package sfGpsDsAuNswS install link in readme"
         if: ${{ github.event.client_payload.sfGpsDsAuNswS == 'true' }}
         run: |
           packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuNswS.outputs.packageVersionId }}"
-          packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNswS\""
-          newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNswS\""
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuNswS\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuNswS\""
           sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
-      # Update sfGpsDsAuVic package install link in readme
+      # Update sfGpsDsAuVic force:force:package:install link in readme
       - name: "Update package sfGpsDsAuVic install link in readme"
         if: ${{ github.event.client_payload.sfGpsDsAuVic == 'true' }}
         run: |
           packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuVic.outputs.packageVersionId }}"
-          packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuVic\""
-          newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuVic\""
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuVic\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuVic\""
           sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
-      # Update sfGpsDsUkGov package install link in readme
+      # Update sfGpsDsUkGov force:force:package:install link in readme
       - name: "Update package sfGpsDsUkGov install link in readme"
         if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' }}
         run: |
           packageVersionId="${{ steps.createPackageVersion-sfGpsDsUkGov.outputs.packageVersionId }}"
-          packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsUkGov\""
-          newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsUkGov\""
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsUkGov\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsUkGov\""
           sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
 
-      # TODO: run prettier on sfdx-package.json
-      #
+      # Update sfGpsDsUkGovFull force:force:package:install link in readme
+      - name: "Update package sfGpsDsUkGov install link in readme"
+        if: ${{ github.event.client_payload.sfGpsDsUkGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          packageVersionId="${{ steps.createPackageVersion-sfGpsDsUkGovFull.outputs.packageVersionId }}"
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsUkGovFull\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsUkGovFull\""
+          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
+
+      # run prettier as sfdx-package.json gets overwritten in a non-prettier way
+      - name: "Run prettier"
+        run: |
+          npm ci
+          npm run prettier
 
       # Create PR for new package version(s)
       - name: "Create PR for new package version"
