vic2 build logic (#323)

diff --git a/.github/workflows/packaging-pr.yml b/.github/workflows/packaging-pr.yml
--- a/.github/workflows/packaging-pr.yml
+++ b/.github/workflows/packaging-pr.yml
@@ -196,6 +196,35 @@ jobs:
           fi
           exit $status2
 
+      - name: "Create package version sfGpsDsAuVic2"
+        id: createPackageVersion-sfGpsDsAuVic2
+        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          set +e
+          npm run auvic2-copy
+          json=$(sfdx package version create --path=sfGpsDsAuVic2Full --installation-key-bypass --wait=20 --definition-file=config/project-scratch-def.json --code-coverage --json)
+          echo "package version create output:"
+          echo $json
+          echo "----"
+          status=$(echo $json | jq '.status')
+          if [ $status == "0" ]; then
+              packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+              echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+          else
+              echo "sfdx package version create failed"
+              exit $status
+          fi
+
+          json2=$(sfdx package version report --package $packageVersionId --json)
+          status2=$(echo $json2 | jq '.status')
+          if [ $status2 == "0" ]; then
+            versionNumber=$(echo $json2 | jq -r '.result.Version')
+            echo "versionNumber=$versionNumber" >> $GITHUB_OUTPUT
+          else
+            echo "sfdx package version report failed"
+          fi
+          exit $status2
+
       - name: "Create package version sfGpsDsFrGov"
         id: createPackageVersion-sfGpsDsFrGov
         if: ${{ github.event.client_payload.sfGpsDsFrGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
@@ -296,6 +325,13 @@ jobs:
           sfdx package install --package ${{ steps.createPackageVersion-sfGpsDsAuVic1.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
           sfdx package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuVic1.outputs.packageVersionId }} --wait=20 --target-org=scratch-org
 
+      # Install new sfGpsDsAuVic2 package in scratch org
+      - name: "Install new sfGpsDsAuVic2 package version in scratch org"
+        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          sfdx package install --package ${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }} --wait=20 --target-org=scratch-org --no-prompt
+          sfdx package uninstall --package ${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }} --wait=20 --target-org=scratch-org
+
       # Install new sfGpsDsFrGov package in scratch org
       - name: "Install new sfGpsFrUkGov package version in scratch org"
         if: ${{ github.event.client_payload.sfGpsDsFrGov == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
@@ -385,6 +421,25 @@ jobs:
           name: "sfGpsDsAuVic ${{ steps.createPackageVersion-sfGpsDsAuVic1.outputs.versionNumber }}"
           prerelease: "true"
           tag: "sfGpsDsAuVic-${{ steps.createPackageVersion-sfGpsDsAuVic1.outputs.versionNumber }}"
+
+      # Update sfGpsDsAuVic2 force:force:package:install link in readme
+      - name: "Update package sfGpsDsAuVic2 install link in readme"
+        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        run: |
+          packageVersionId="${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }}"
+          packageLinkRegex="https:\/\/test\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}\" title=\"sfGpsDsAuVic2Full\""
+          newPackageLink="https://test.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}\" title=\"sfGpsDsAuVic2Full\""
+          sed -E -i "s,${packageLinkRegex},${newPackageLink}," README.md
+
+      # Create sfGpsDsAuVic2 GH release
+      - name: "Release package sfGpsDsAuVic2"
+        if: ${{ github.event.client_payload.sfGpsDsAuVic2 == 'true' || github.event.client_payload.sfGpsDs == 'true' }}
+        uses: ncipollo/release-action@v1
+        with:
+          body: "Sandbox unmanaged package: [https://test.salesforce.com/packaging/installPackage.apexp?p0=${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }}](https://test.salesforce.com/packaging/installPackage.apexp?p0=${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.packageVersionId }})"
+          name: "sfGpsDsAuVic2 ${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.versionNumber }}"
+          prerelease: "true"
+          tag: "sfGpsDsAuVic2-${{ steps.createPackageVersion-sfGpsDsAuVic2.outputs.versionNumber }}"
 
       # Update sfGpsDsFrGov force:force:package:install link in readme
       - name: "Update package sfGpsDsFrGov install link in readme"
